### ISSUE TITLE
Refactor Task Spec Tree (STG-14)

### ISSUE THREAD

**Issue by calexh-sar** [sartography/cr-connect-bpmn#18]
Currently, when working on STG-9 / cr-connect-bpmn#17 I added a bunch of helper code. It would be good to break this down into its own file, clean up the follow tree function so it is shorter and more clear, and document the heck out of whatever is left

**Comment by danfunk** [comment]
This is likely very outdated, and can be subsummed within the larger mission to refactor the bpmn for ReConnect.
