### ISSUE TITLE
Additional Refactoring Of Task Spec Tree (STG-13)

### ISSUE THREAD

**Issue by calexh-sar** [sartography/cr-connect-bpmn#19]
When working on STG-9, I had to jump through some hoops because the tree structure wasn't filled out 100% correctly.

The proper thing would have been to go and take care of the outgoing_sequence_flows that are a slightly different structure. Currently, I am not updating these at all, but the tree navigator follows them.

These would also need to be updated should the number of PMI entries change through a token reset or a backtracking exclusive gateway. 

To accomplish this correctly, I would need to teardown/rebuild both the Outputs and the sequence flows of the parent, the current items and probably also the closing gateway.

At the same time, the parent task spec to the PMI was ending up with 2 outputs - 1 for the PMI and one for the new ParallelGateway that I created.   This should only be the one output after patching the tree.

**Comment by danfunk** [comment]
so much work has happened in the task spec tress since this was written, while refactoring is certainly in order, I don't think this adds to the conversation.
